<a href="https://colab.research.google.com/github/jv-mx/TLC-DC/blob/main/DS_C2_SC2_JONATHANVILLAVICENCIO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TLG - Programación en Python
## Subcompetencia: Pandas y Numpy en Python
## Reto: Análisis del Progreso de vacunación mundial
### Analista: Jonathan Villavicencio

Objetivos:<br>

* Emplea los conocimientos adquiridos para obtener información a partir de grandes volúmenes de datos que describen una situación real.
* Construye scripts en Python, incluyendo las plataformas NumPy y Pandas, para recuperar información en formato tabular de un archivo,<br> seleccionar información relevante y generar nuevos datos o resúmenes que puedan ser almacenados en un archivo de salida.
* Resuelve un problema sintetizando datos para obtener resultados concluyentes.

### Libreta en Google Colab con secciones documentadas

### Recuperar la información del archivo 
a. Extraer la información del archivo

In [4]:
import pandas as pd
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows

In [5]:
df = pd.read_csv('/content/country_vaccinations.csv', parse_dates=["date"])
df2 = pd.read_csv('/content/country_vaccinations_by_manufacturer.csv', parse_dates=["date"])

### Obtener la estructura y tipos de dato de cada columna
b. Mostrar la estructura y tipos de datos de cada columna para identificar qué operaciones puedes realizar con cada una de ellas,<br> asegurandote que las columnas con fechas sean del tipo datetime64.

In [6]:
print('Estructuras de DataFrames:\n\ndf:country_vaccinations\n')
print(df.info())
display(df.head())

print('\ndf2:country_vaccinations_by_manufacturer\n')
print(df2.info())
display(df2.head())

Estructuras de DataFrames:

df:country_vaccinations

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86512 entries, 0 to 86511
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              86512 non-null  object
 1   iso_code                             86512 non-null  object
 2   date                                 86512 non-null  datetime64[ns]
 3   total_vaccinations                   43607 non-null  float64
 4   people_vaccinated                    41294 non-null  float64
 5   people_fully_vaccinated              38802 non-null  float64
 6   daily_vaccinations_raw               35362 non-null  float64
 7   daily_vaccinations                   86213 non-null  float64
 8   total_vaccinations_per_hundred       43607 non-null  float64
 9   people_vaccinated_per_hundred        41294 non-null  float64
 10  people_fully_vaccinated_per_hundred  38802 non-null  float64
 11  daily_vaccinations_per_million       86213 non-null  float64
 12  vaccines                             86512 non-null  object
 13  source_name                          86512 non-null  object
 14  source_website                       86512 non-null  object
dtypes: datetime64[ns](1), float64(9), object(5)
memory usage: 9.9+ MB
None

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/

df2:country_vaccinations_by_manufacturer

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35623 entries, 0 to 35622
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   location            35623 non-null  object
 1   date                35623 non-null  datetime64[ns]
 2   vaccine             35623 non-null  object
 3   total_vaccinations  35623 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 1.1+ MB
None

    location       date             vaccine  total_vaccinations
0  Argentina 2020-12-29             Moderna                   2
1  Argentina 2020-12-29  Oxford/AstraZeneca                   3
2  Argentina 2020-12-29   Sinopharm/Beijing                   1
3  Argentina 2020-12-29           Sputnik V               20481
4  Argentina 2020-12-30             Moderna                   2

### Cantidad de vacunas aplicadas de cada compañía
c. Determinar la cantidad de vacunas aplicadas de cada compañía (en base a como lo reporta cada país en la columna vaccines)

#NOTA:
En este caso, la segunda parte de la instrucción ya que la columna *''vaccines''* es referente a un subconjunto de datos denominado *''country_vaccinations_by_manufacturer.csv''*  de manera que se presentan ambos casos aplicables a la consigna para su revisión.

In [7]:
vacCO = df2.groupby(['vaccine'], as_index=False)['total_vaccinations'].sum()
vacCO['total_vaccinations'] = vacCO['total_vaccinations'].apply(lambda x: "{:,.0f}".format(x))

print('Vacunas aplicadas de cada compañia:')
display(vacCO.head())

vacCO2 = df2.groupby(['location','vaccine'], as_index=False)['total_vaccinations'].sum()
vacCO2['total_vaccinations'] = vacCO2['total_vaccinations'].apply(lambda x: "{:,.0f}".format(x))

print('Vacunas aplicadas de cada compañia en relación al país')
display(vacCO2.head())

Vacunas aplicadas de cada compañia:

           vaccine total_vaccinations
0          CanSino        271,397,675
1          Covaxin              3,572
2  Johnson&Johnson     12,611,375,881
3          Moderna    103,072,147,621
4          Novavax          8,268,113

Vacunas aplicadas de cada compañia en relación al país

    location             vaccine total_vaccinations
0  Argentina             CanSino         53,950,431
1  Argentina             Moderna        893,386,753
2  Argentina  Oxford/AstraZeneca      5,618,580,845
3  Argentina     Pfizer/BioNTech      1,307,660,776
4  Argentina   Sinopharm/Beijing      5,713,239,160

### Cantidad de vacunas aplicadas en todo el mundo
d. Obtener la cantidad de vacunas aplicadas en todo el mundo

In [8]:
glob_vacc = df['total_vaccinations'].sum()

print(f'La cantidad de vacunas aplicadas en todo el mundo fue de: {glob_vacc:,.0f}.')

La cantidad de vacunas aplicadas en todo el mundo fue de: 2,002,854,013,761.

### Promedio de vacunas aplicadas por país
e. Calcular el promedio de vacunas aplicadas por país

In [9]:
vaccAVRG = df.groupby(['country'], as_index=False)['total_vaccinations'].mean()
vaccAVRG = pd.DataFrame(data=vaccAVRG).rename(columns={'total_vaccinations':'vaccine_avrg'}) 
vaccAVRG['vaccine_avrg'] = vaccAVRG['vaccine_avrg'].apply(lambda x: "{:,.2f}".format(x))

vaccAVRG.head()

       country  vaccine_avrg
0  Afghanistan  2,566,117.96
1      Albania  1,191,695.42
2      Algeria  9,956,085.92
3      Andorra     58,277.21
4       Angola  6,074,066.30

### Cantidad de vacunas aplicadas el día 29/01/21
f. Determinar la cantidad de vacunas aplicadas el día 29/01/21 en todo el mundo

In [10]:
vcc_291021 = (df[df['date']=='29/01/21'])['total_vaccinations'].sum()
 
print(f'La cantidad de vacunas aplicadas el día 29/01/21 en todo el mundo fue de: {vcc_291021:,.0f}.')

La cantidad de vacunas aplicadas el día 29/01/21 en todo el mundo fue de: 82,952,931.

### Dataframe nuevo llamado conDiferencias
g. Crear un dataframe nuevo denoninado conDiferencias que contenga los datos originales y una columna derivada (diferencias)<br> con las diferencias de aplicación entre las columnas daily_vaccionations y daily_vaccionations_raw

In [11]:
conDiferencias = df.copy()
conDiferencias['diferencias'] = conDiferencias['daily_vaccinations'] - conDiferencias['daily_vaccinations_raw']

conDiferencias.tail()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website,diferencias
86507,Zimbabwe,ZWE,2022-03-25,8691642.0,4814582.0,3473523.0,139213.0,69579.0,57.59,31.90,23.02,4610.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,-69634.0
86508,Zimbabwe,ZWE,2022-03-26,8791728.0,4886242.0,3487962.0,100086.0,83429.0,58.25,32.38,23.11,5528.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,-16657.0
86509,Zimbabwe,ZWE,2022-03-27,8845039.0,4918147.0,3493763.0,53311.0,90629.0,58.61,32.59,23.15,6005.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,37318.0
86510,Zimbabwe,ZWE,2022-03-28,8934360.0,4975433.0,3501493.0,89321.0,100614.0,59.20,32.97,23.20,6667.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,11293.0
86511,Zimbabwe,ZWE,2022-03-29,9039729.0,5053114.0,3510256.0,105369.0,103751.0,59.90,33.48,23.26,6874.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,-1618.0

### Obtener la diferencia de tiempo
h. Obtener el período de tiempo entre el registro con fecha más reciente y el registro con fecha más antigua

In [12]:
time_period = (df['date'].max() - df['date'].min()).days

print('El tiempo transcurrido ente el registro más reciente y el más antiguo es de: ' + str(time_period) + ' días.')

El tiempo transcurrido ente el registro más reciente y el más antiguo es de: 482 días.

### Dataframe nuevo llamado conCantidad
i. Crear un dataframe nuevo denominado conCantidad que contenga los datos originales y una columna derivada (canVac)<br> con la cantidad de vacunas utilizadas cada día (usar la columna vaccines y separar por el carácter / )

#NOTA:
De acuerdo con la ultima actualización del set de datos <a href="https://www.kaggle.com/datasets/gpreda/covid-world-vaccination-progress">COVID-19 World Vaccination Progress</a> *(versión 249 - 2022/03/31)* la columna *''vaccines''* está ligada al sub conjunto de datos llamado *''country_vaccinations_by_manufacturer.csv''* el cual contiene la información de cada vacuna y el caracter "/" no define una separación entre vacunas. 

Por lo que la consigna para este ejercicio no sólo es confusa, sino poco adecuada a los datos que tenemos disponibles. 

Sin embargo, mi propuesta de extracción para cumplir con la visualñisación solicitada es:

* Tomar el subconjunto de datos de la columna *''vaccines''*
* Ordenarlos de manera ascendente con la lógica : locación, fecha, vacuna
* Agrupar y obtener la diferencia de las vacunas de *''hoy''* y las de el día anterior para así obtener las vacunas aplicadas cada día por cada compañía,

In [20]:
conCantidad = df2.copy()

conCantidad = conCantidad.sort_values(by=['location', 'date', 'vaccine'])
conCantidad['canVac'] = conCantidad.groupby(['location', 'vaccine'])['total_vaccinations'].diff()
conCantidad['canVac'] = conCantidad['canVac'].fillna(0)
conCantidad['canVac'] = conCantidad['canVac'].apply(lambda x: "{:,.0f}".format(x))

conCantidad

        location       date             vaccine  total_vaccinations canVac
0      Argentina 2020-12-29             Moderna                   2      0
1      Argentina 2020-12-29  Oxford/AstraZeneca                   3      0
2      Argentina 2020-12-29   Sinopharm/Beijing                   1      0
3      Argentina 2020-12-29           Sputnik V               20481      0
4      Argentina 2020-12-30             Moderna                   2      0
...          ...        ...                 ...                 ...    ...
31496    Uruguay 2022-03-28     Pfizer/BioNTech             2475706  2,124
31497    Uruguay 2022-03-28             Sinovac             3247932      0
31498    Uruguay 2022-03-29  Oxford/AstraZeneca               90732      0
31499    Uruguay 2022-03-29     Pfizer/BioNTech             2476595    889
31500    Uruguay 2022-03-29             Sinovac             3247932      0

[35623 rows x 5 columns]

### Dataframe llamado antes20
j. Generar un dataframe denominado antes20 con todos los registros que se hayan realizado antes del 20 de diciembre de 2020.

In [14]:
antes20 = df[df['date']<'2020/12/20']
antes20.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
13403,Canada,CAN,2020-12-14,5.0,5.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html
13404,Canada,CAN,2020-12-15,727.0,727.0,NaN,722.0,722.0,0.00,0.00,NaN,19.0,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html
13405,Canada,CAN,2020-12-16,3025.0,3025.0,NaN,2298.0,1510.0,0.01,0.01,NaN,40.0,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html
13406,Canada,CAN,2020-12-17,7279.0,7279.0,NaN,4254.0,2425.0,0.02,0.02,NaN,64.0,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html
13407,Canada,CAN,2020-12-18,11296.0,11296.0,NaN,4017.0,2823.0,0.03,0.03,NaN,74.0,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html

### Dataframe llamado pfizer
k. Obtener un dataframe denominado pfizer con todos los registros donde se haya utilizado la vacuna Pfizer.

In [15]:
pfizer = df[df['vaccines'].str.contains(r'.*Pfizer.*')]
pfizer.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/

### Almacenar los dataframes
l. Almacenar los dataframes generados (conDiferencias,conCantidad,antes20 y pfizer) en un archivo de Excel denominado resultadosReto.xlsx,<br> donde cada dataframe ocupe una hoja diferente. Se recomienda ver la documentación de pd.ExcelWriter

### NOTA: 
En este caso el ciclo se asegura de retirar los hipervínculos ya que el formato xlsx, a diferencia de csv, los almacena como objetos y el numero es mucho más limitado que el texto plano.

In [18]:

workbook = Workbook()
sheet_names = ['conDiferencias','conCantidad', 'antes20', 'pfizer']


for sheet_name, df in zip(sheet_names, [conDiferencias,conCantidad, antes20, pfizer]):
    worksheet = workbook.create_sheet(title=sheet_name)
    df['date'] = pd.to_datetime(df['date']).dt.strftime('%Y-%m-%d')
    rows = dataframe_to_rows(df, index=False)

    for r_idx, row in enumerate(rows, start=1):
        for c_idx, value in enumerate(row, start=1):
            worksheet.cell(row=r_idx, column=c_idx, value=value)

    for cell in worksheet['A']:
        if cell.hyperlink is not None:
            cell.hyperlink = None

workbook.remove(workbook['Sheet'])
workbook.save('resultadosReto.xlsx')